version: '2'

# Note: links are not needed in docker-compose v2.
# https://medium.com/@giorgioto/docker-compose-yml-from-v1-to-v2-3c0f8bb7a48e#.n1ad9b83t

services:
  dns:
    # image: praqma/dns
    build: dns/
    dns: 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /opt/toolbox/dns/toolbox.example.com.zone:/var/named/toolbox.example.com.zone

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    # Ports need not be mapped to the host. Staci interferes with these ports.
    # Cadvisor will be available on it's own IP anyway. So no need to map this.
    # ports:
    #   - "8080:8080/tcp"

  multitool:
    image: praqma/network-multitool


