version: '2'

# Note: links are not needed in docker-compose v2.
# https://medium.com/@giorgioto/docker-compose-yml-from-v1-to-v2-3c0f8bb7a48e#.n1ad9b83t

services:
  dns:
    # image: praqma/dns
    build: dns/
    dns: 127.0.0.1
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /opt/toolbox/dns/toolbox.example.com.zone:/var/named/toolbox.example.com.zone

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    # Ports need not be mapped to the host. Staci interferes with these ports.
    # Cadvisor will be available on it's own IP anyway. So no need to map this.
    # ports:
    #   - "8080:8080/tcp"

  www:
    # This web server will serve a very simple index.html page, 
    # which is build by ocdd.sh - while ocdd.sh builds up the iptables rules, and dns entries etc.
    # It will mount the index.html from persistent storage.
    # This service will also map port 80 on the dockerhost.
    # If this conflicts with anything else running on the dockerhost, such as another docker-compose app / container,
    #   feel free to disable it's port mapping. 
    image: nginx
    volumes:
      - /opt/toolbox/www/index.html:/usr/share/nginx/html/index.html
    ports:
      - "80:80/tcp"


